---
# Setup common elements for the application host

- name: Update apt cache
  become: True
  apt:
   update_cache: yes

- name: Install common packages
  become: True
  apt: name={{ item }} state=present
  with_items: "{{ packages }}"

- name: UFW OpenSSH
  become: True
  ufw: rule=limit port=ssh proto=tcp

- name: UFW Enabled
  become: True
  ufw: state=enabled

- name: sshd basic configuration
  become: True
  template: src=sshd_config.j2
    dest=/etc/ssh/sshd_config
    backup=yes
    owner=0 group=0 mode=0600
    validate='/usr/sbin/sshd -T -f %s'

- name: StrongSwan Packages
  become: True
  apt: name={{ item }} state=present
  with_items:
    - strongswan
    - strongswan-pki
    - libcharon-extra-plugins
    - libcharon-extauth-plugins
    - libstrongswan-extra-plugins
    - libtss2-tcti-tabrmd0

- name: VPN Ports
  become: True
  ufw: rule=allow port={{ item }} proto=udp
  with_items:
    - 500
    - 4500

- name: Root CA Key
  become: True
  shell: "pki --gen --type rsa --size 4096 --outform pem > {{ ipsec_dir }}/private/ca-key.pem"
  args:
    creates: "{{ ipsec_dir }}/private/ca-key.pem"

- name: Root CA Certificate
  become: True
  shell: "pki --self --ca --lifetime 3650 --in {{ ipsec_dir }}/private/ca-key.pem --type rsa --dn \"CN={{ ca_cert_cn }}\" --outform pem > {{ ipsec_dir }}/cacerts/ca-cert.pem"
  args:
    creates: "{{ ipsec_dir }}/cacerts/ca-cert.pem"

- name: CA Private Key
  become: True
  shell: "pki --gen --type rsa --size 4096 --outform pem > {{ ipsec_dir }}/private/server-key.pem"
  args:
    creates: "{{ ipsec_dir }}/private/server-key.pem"

