---
# Setup common elements for the application host

- name: Update apt cache
  become: True
  apt:
   update_cache: yes

- name: Install common packages
  become: True
  apt: name={{ item }} state=present
  with_items: "{{ packages }}"

- name: UFW OpenSSH
  become: True
  ufw: rule=limit port=ssh proto=tcp

- name: UFW Enabled
  become: True
  ufw: state=enabled

- name: sshd basic configuration
  become: True
  template: src=sshd_config.j2
    dest=/etc/ssh/sshd_config
    backup=yes
    owner=0 group=0 mode=0600
    validate='/usr/sbin/sshd -T -f %s'

- name: StrongSwan Packages
  become: True
  apt: name={{ item }} state=present
  with_items:
    - strongswan
    - strongswan-pki
    - libcharon-extra-plugins
    - libcharon-extauth-plugins
    - libstrongswan-extra-plugins
    - libtss2-tcti-tabrmd0

- name: VPN Ports
  become: True
  ufw: rule=allow port={{ item }} proto=udp
  with_items:
    - 500
    - 4500

- name: Root CA Key
  become: True
  shell: "pki --gen --type rsa --size 4096 --outform pem > {{ ipsec_dir }}/private/ca-key.pem"
  args:
    creates: "{{ ipsec_dir }}/private/ca-key.pem"

- name: Root CA Certificate
  become: True
  shell: "pki --self --ca --lifetime 3650 --in {{ ipsec_dir }}/private/ca-key.pem --type rsa --dn \"CN={{ ca_cert_cn }}\" --outform pem > {{ ipsec_dir }}/cacerts/ca-cert.pem"
  args:
    creates: "{{ ipsec_dir }}/cacerts/ca-cert.pem"

- name: CA Private Key
  become: True
  shell: "pki --gen --type rsa --size 4096 --outform pem > {{ ipsec_dir }}/private/server-key.pem"
  args:
    creates: "{{ ipsec_dir }}/private/server-key.pem"

- name: VPN Server Certificate
  become: True
  args:
    creates: "{{ ipsec_dir }}/certs/server-cert.pem"
  shell: |
    pki --pub --in {{ ipsec_dir }}/private/server-key.pem --type rsa \
    | pki --issue --lifetime 1825 \
        --cacert {{ ipsec_dir }}/cacerts/ca-cert.pem \
        --cakey {{ ipsec_dir }}/private/ca-key.pem \
        --dn 'CN={{ vpn_fqdn }}' --san {{ vpn_fqdn }} \
        --flag serverAuth --flag ikeIntermediate --outform pem \
        > {{ ipsec_dir }}/certs/server-cert.pem

- name: StrongSwan Configuration
  become: True
  template:
    src: ipsec.conf.j2
    dest: /etc/ipsec.conf
    owner: root
    group: root
    mode: 0644
    backup: yes
  notify: Restart StrongSwan


- name: Add server key to ipsec.secrets
  become: True
  lineinfile:
    path: /etc/ipsec.secrets
    line: ': RSA "server-key.pem"'
  notify: Restart StrongSwan
