# Default packages for host setup
packages:
  - htop
  - tree
  - net-tools
  - acl
  - make
  - build-essential
  - libssl-dev
  - zlib1g-dev
  - libbz2-dev
  - libreadline-dev
  - libsqlite3-dev
  - curl
  - git
  - libncursesw5-dev
  - xz-utils
  - tk-dev
  - libxml2-dev
  - libxmlsec1-dev
  - libffi-dev
  - liblzma-dev

pyenv_dir:  /usr/local/python3
pyenv_path: "{{ pyenv_dir }}/.pyenv"
